# Generated by Django 4.1.4 on 2022-12-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyuser', models.CharField(max_length=25)),
                ('follower', models.IntegerField()),
                ('picture', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistName', models.CharField(max_length=100)),
                ('numbSongs', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('tracksLink', models.CharField(max_length=100)),
                ('uri', models.CharField(max_length=100)),
            ],
        ),
    ]
