# Generated by Django 4.1.4 on 2022-12-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylists',
            name='spotifyuser',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
