# Generated by Django 4.1.4 on 2022-12-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_userplaylists_spotifyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistName', models.CharField(max_length=100)),
                ('artistName', models.CharField(max_length=100)),
                ('songName', models.CharField(max_length=100)),
                ('songLength', models.TimeField()),
                ('albumName', models.CharField(max_length=100)),
                ('albumUri', models.CharField(max_length=100)),
            ],
        ),
    ]
