# Generated by Django 4.1.4 on 2022-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlistinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistinformation',
            old_name='albumUri',
            new_name='albumUrl',
        ),
        migrations.AddField(
            model_name='playlistinformation',
            name='artistUrl',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlistinformation',
            name='songLength',
            field=models.CharField(max_length=10),
        ),
    ]
