# Generated by Django 4.1.4 on 2022-12-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='null', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='null', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='spotifyuser',
            field=models.CharField(default='andre008', max_length=25),
            preserve_default=False,
        ),
    ]
