# Generated by Django 4.1.4 on 2022-12-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinformation_userplaylists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplaylists',
            name='spotifyuser',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
        migrations.DeleteModel(
            name='UserPlaylists',
        ),
    ]
